config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :users, only: [:new, :create, :show]
  resources :expenses, only: [:new, :create, :show, :destroy, :edit, :update]
  resources :budgets, only: [:edit, :update]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/signup',  to: 'users#new'
  get '/welcome', to: 'sessions#welcome'
  get '/help', to: 'static_pages#help'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :user
  validates_presence_of :amount
  validates_numericality_of :amount
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :expenses

  validates_presence_of :name
  validates_presence_of :description
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user
  belongs_to  :category

  validates_presence_of :due_date
  validates_presence_of :description

  validates_numericality_of :amount_due
  validates_numericality_of :amount_paid

  attribute :paid, :boolean, default: false

  after_commit :apply_payment_to_expense, on: [:create, :update]
  # before_update :prevent_update_if_expense_is_paid, :if => :paid
  before_update :prevent_update_if_payment_exceeds_limits, :if => :amount_paid_changed?

  before_save :payment_exceeds_amount_due?
  before_save :payment_exceeds_remaining_budget_balance?

  private

  def prevent_update_if_payment_exceeds_limits
    if payment_exceeds_remaining_budget_balance? && payment_exceeds_amount_due?
      true
    else
      self.errors[:base] << 'Cannot apply payment because it exceeds limits'
      throw(:abort)
    end
  end

  def payment_exceeds_remaining_budget_balance?
    if payment_difference > user.budget.amount
      self.errors[:base] << 'Cannot apply payment amount over remaining budget amount'
      throw(:abort)
    else
      true
    end
  end

  def payment_exceeds_amount_due?
    if amount_paid > amount_due
      self.errors[:base] << 'Cannot apply payment amount (total) over amount due'
      throw(:abort)
    else
      true
    end
  end

  def apply_payment_to_expense
    set_paid_status
    apply_payment_to_budget
  end

  def set_paid_status
    if amount_paid == amount_due
      self.update_column(:paid, true)
    end
  end

  def apply_payment_to_budget
    user.budget.update_column(
      :amount,
      user.budget.amount - payment_difference
    )
  end

  def payment_difference
    prev_amount_paid = amount_paid_before_last_save || 0.0
    amount_paid - prev_amount_paid
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one :budget
  accepts_nested_attributes_for :budget
  has_many :expenses

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates_presence_of :username

  validates :email, presence: true, uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }, length: { maximum: 255 }

  before_save :downcase_email
  has_secure_password

  private

  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  before_action :authenticate

  private

  def authenticate
    if current_user.nil?
      flash[:error] = "Please log in to view this page."
      redirect_to login_path
    end
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :correct_user?,  only: [:edit, :update]

  def new
    @budget = Budget.new
  end

  def edit
    set_budget
  end

  def update
    set_budget
    if @budget.update(amount: @budget.amount + params[:budget][:amount].to_f)
      redirect_to user_path(@budget.user)
    else
      flash.now[:error] = @budget.errors.full_messages[0]
      render 'edit'
    end
  end

  private

  def correct_user?
    set_budget
    unless current_user?(@budget.user)
      redirect_to user_path(current_user)
    end
  end

  def set_budget
    @budget = Budget.find(params[:id])
  end

  def budget_params
    params.require(:budget).permit(:amount)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :correct_user?,  only: [:edit, :update]

  def new
    @expense = Expense.new
  end

  def create
    @expense = Expense.new(expense_params)
    @expense.user = current_user
    if @expense.save
      redirect_to user_path(@expense.user)
    else
      flash.now[:error] = @expense.errors.full_messages[0]
      render 'new'
    end
  end

  def edit
    set_expense
  end

  def update
    set_expense
    if @expense.update(amount_paid: @expense.amount_paid + expense_params[:amount_paid].to_f)
      redirect_to user_path(@expense.user)
    else
      flash.now[:error] = @expense.errors.full_messages[0]
      render 'edit'
    end
  end

  def show
    set_expense
    @user = User.find(@expense.user_id)
    @user_expenses = Expense.where(user_id: @expense.user_id)
  end

  def destroy
    set_expense
    user = current_user
    @expense.destroy
    redirect_to user_path(user)
  end

  private

  def correct_user?
    set_expense
    unless current_user?(@expense.user)
      redirect_to user_path(current_user)
    end
  end

  def set_expense
    @expense = Expense.find(params[:id])
  end

  def expense_params
  params.require(:expense).permit(:due_date, :amount_due, :amount_paid, :paid, :description, :user_id, :category_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action  :authenticate , only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user
    else
      flash.now[:error] = "Invalid username/password combination."
      render 'new', status: :unauthorized
    end
  end

  def welcome
  end

  def destroy
    log_out
    redirect_to root_url, flash: { info: 'You have  successfully logged out.' }
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action  :authenticate

  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action  :authenticate , only: [:new, :create]
  before_action :correct_user?,  only: [:show]
  before_action :logged_in_user?,  only: [:new]

  def new
    @user = User.new
    @user.build_budget
  end

  def create
    @user = User.new(user_params)
    if @user.save
      payload = { user_id: @user.id }
      log_in(@user)
      redirect_to @user
    else
      flash.now[:error] =  @user.errors.full_messages[0]
      render 'new'
    end
  end

  def show
    set_user
  end

  private

  # make sure correct user is viewing the page
  def correct_user?
    set_user
    unless current_user?(@user)
      redirect_to user_path(current_user)
    end
  end

  # make sure logged in user can't view sign up page
  def logged_in_user?
    if logged_in?
      redirect_to user_path(current_user)
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    # params.fetch(:user, {})
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :salt, :encrypted_password, budget_attributes: [:amount])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user?(user)
    user && user == current_user
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/budgets/edit.html.erb
<%= stylesheet_link_tag "custom" %>
<div class="container budget-editForm">
  <h1 class="text-center">Add Money to Your Budget</h1>
  <% provide(:title, 'Add Money to Your Budget') %>
  <div class="row text-center">
    <div class="col-md-6 col-md-offset-3">
      <div class="d-flex flex-column mb-3">
        <%= form_with(model: @budget, local: true) do |f| %>
          <div  class="amount-form-label">
            <%= f.label :amount, "Additional Amount to Budget" %>
          </div>
          <div class="amount-form-field">
            <%= f.number_field :amount, :step => 0.01, :value => 0.00 %>
          </div>
          <div class="form-submit-button">
            <%= f.submit "Add Money", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/expenses/create.html.erb
<h1>Expenses#create</h1>
<p>Find me in app/views/expenses/create.html.erb</p>

app/views/expenses/edit.html.erb
<%= stylesheet_link_tag "custom" %>
<div class="container expense-editForm">
  <h1 class="text-center">Apply Payment to Expense</h1>
  <% provide(:title, 'Apply Payment to Expense') %>
  <div class="row text-center">
    <div class="col-md-6 col-md-offset-3">
      <div class="d-flex flex-column mb-3">
        <%= form_with(model: @expense, local: true) do |f| %>
          <div  class="amountPaid-form-label">
            <%= f.label :amount_paid, "Amount Paid" %>
          </div>
          <div class="amountPaid-form-field">
            <%= f.number_field :amount_paid, :step => 0.01, :value => 0.00 %>
          </div>
          <div class="form-submit-button">
            <%= f.submit "Apply Payment", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/expenses/new.html.erb
<%= stylesheet_link_tag "custom" %>
<div class="container expense-createForm">
  <h1 class="text-center">Add New Expense</h1>
  <% provide(:title, 'Add New Expense') %>
  <div class="row text-center">
    <div class="col-md-6 col-md-offset-3">
      <div class="d-flex flex-column mb-3">
        <%= form_with(model: @expense, local: true) do |f| %>
          <div class="description-form-label">
            <%= f.label :description %>
          </div>
          <div class="description-form-field">
            <%= f.text_field :description %>
          </div>
          <div class="dueDate-form-label">
            <%= f.label :due_date, "Due Date" %>
          </div>
          <div class="dueDate-form-field">
            <%= f.date_field :due_date %>
          </div>
          <div class="amountDue-form-label">
            <%= f.label :amount_due, "Amount Due" %>
          </div>
          <div class="amountDue-form-field">
            <%= f.number_field :amount_due, :step => 0.01 %>
          </div>
          <div  class="amountPaid-form-label">
            <%= f.label :amount_paid, "Amount Paid" %>
          </div>
          <div class="amountPaid-form-field">
            <%= f.number_field :amount_paid, :step => 0.01 %>
          </div>
          <div  class="category-id-form-label">
            <%= f.label :category_id, "Category" %>
          </div>
          <div class="category-id-form-field">
            <%= f.collection_select(:category_id, Category.all, :id, :name) %>
          </div>
          <div class="form-submit-button">
            <%= f.submit "Add Expense", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/expenses/show.html.erb
<div class="container expenses">
  <h1 class="expenses-pageHeader text-center">
    <%= "Expense just added falls under the category: #{@expense.category.name}" %>
  </h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script>
      $( document ).ready(function(){
      $('#mycarousel').carousel();
      });
    </script>
  </head>

  <body>
    <%= render "shared/header" %>
    <% flash.each do |type, msg| %>
      <div class="alert alert-info text-center">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
          <% if logged_in? %>
            <%= link_to user_path(current_user) do %>
              Budget App<i class="glyphicon glyphicon-stats"></i>
            <% end %>
          <% else %>
            <%= link_to root_path do %>
              Budget App<i class="glyphicon glyphicon-stats"></i>
            <% end %>
          <% end %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li>
            <%= link_to logout_path do %>
              Log Out<i class="glyphicon glyphicon-log-out"></i>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to signup_path do %>
              Sign Up<i class="glyphicon glyphicon-plus-sign"></i>
            <% end %>
          </li>
          <li>
            <%= link_to login_path do %>
              Log In<i class="glyphicon glyphicon-user"></i>
            <% end %>
          </li>
        <% end %>
        <li>
          <%= link_to help_path do %>
            Help<i class="glyphicon glyphicon-cog"></i>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/static_pages/help.html.erb
<div class="helpPage-transBox">
  <h2 class="helpPage-text text-center">
    Here are some quick tidbits about BudgetApp the site.
  </h2>
  <ul class="helpPage-HelpList">
    <li class="helpPage-HelpList-HelpItem">Click the sign up link at the top to sign up for an account to start tracking your expenses</li>
    <li class="helpPage-HelpList-HelpItem">Click the login button at the top to login and see your expenses.</li>
    <li class="helpPage-HelpList-HelpItem">When logged in and on your profile page click on the Add Expense link to add a new expense.</li>
    <li class="helpPage-HelpList-HelpItem">When logged in and on your profile page click on the Add to Budget link to add more money to your budget.</li>
    <li class="helpPage-HelpList-HelpItem">There two charts that you see  will tell you how much money you spend on each category.</li>
  </ul>
</div>

app/views/static_pages/home.html.erb
<div class="homePage-transBox">
  <p class="homePage-text text-center">
    Welcome to BudgetApp the site. Sign up or Login and Begin Tracking Your Expenses and See Where Your Money is Going. (Sample Below)
  </p>
  <div class="homePage-barChartSample">
    <%= column_chart Expense.limit(5).order('RANDOM()').joins(:category).group('categories.name').sum(:amount_paid), prefix: "$" %>
  </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<%= stylesheet_link_tag "custom" %>

<div class="container user-signupForm">
  <h1 class="text-center">New User Sign Up</h1>
  <% provide(:title, 'Sign Up') %>
  <div class="row text-center">
    <div class="col-md-6 col-md-offset-3">
      <div class="d-flex flex-column mb-3">
        <%= form_with(model: @user, local: true) do |f| %>
          <div class="username-form-label">
            <%= f.label :username %>
          </div>
          <div class="username-form-field">
            <%= f.text_field :username %>
          </div>
          <%= f.fields_for :budget do |budget_fields| %>
            <div class="budget-form-label">
              <%= budget_fields.label :amount, 'Budget Amount' %>
            </div>
            <div class="budget-form-field">
              <%= budget_fields.number_field :amount, :step => 0.01 %>
            </div>
          <% end %>
          <div class="email-form-label">
            <%= f.label :email %>
          </div>
          <div class="email-form-field">
            <%= f.email_field :email %>
          </div>
          <div  class="password-form-label">
            <%= f.label :password %>
          </div>
          <div class="password-form-field">
            <%= f.password_field :password %>
          </div>
          <div class="password-confirmation-form-label">
            <%= f.label :password_confirmation, "Password Confirmation" %>
          </div>
          <div class="password-confirmation-form-field">
            <%= f.password_field :password_confirmation %>
          </div>
          <div class="form-submit-button">
            <%= f.submit "Create my account", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= stylesheet_link_tag "custom" %>
<div class="user-PageWrapper">
  <h1 class="text-center user-profileHeader"> <%= "Welcome #{@user.username}, you have a budget of #{number_to_currency(@user.budget.amount)} remaining." %> </h1>
  <div class="user-row">
    <div class="user-column">
      <div class="user-ModificationColumn">
        <div class="user-InteractionBox">
          <div class="user-InteractionHeader">
            Add an Expense or Add Money to your Budget!
          </div>
          <div class="user-addBudget">
            <%= link_to edit_budget_path(@user.budget) do %>
              Add More Money To Your Budget <i class="glyphicon glyphicon-usd"></i>
            <% end %>
          </div>
          <div class="user-addExpense">
            <%= link_to new_expense_path do %>
              Add An Expense <i class="glyphicon glyphicon-book"></i>
            <% end %>
          </div>
        </div>
        <div class="user-tableContainer table-responsive">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th scope="col">Expense</th>
                <th scope="col">Amount Due</th>
                <th scope="col">Amount Paid</th>
                <th scope="col">Due Date</th>
                <th scope="col">Paid</th>
                <th scope="col">Apply Payment</th>
                <th scope="col">Delete Expense</th>
              </tr>
            </thead>
            <tbody>
              <% @user.expenses.each_with_index do |expense, index| %>
                <tr>
                  <td><%= expense.description %></td>
                  <td><%= number_to_currency(expense.amount_due) %></td>
                  <td><%= number_to_currency(expense.amount_paid) %></td>
                  <td><%= expense.due_date %></td>
                  <td>
                    <% paid_status_icon_class = expense.paid ? 'glyphicon glyphicon-ok' : 'glyphicon glyphicon-remove' %>
                    <span class="<%= paid_status_icon_class %>"></span>
                  </td>
                  <td>
                    <% payment_button_class = expense.paid ? 'btn btn-success disabled' : 'btn btn-success' %>
                    <%= link_to 'Add payment', edit_expense_path(expense), class: payment_button_class %>
                  </td>
                  <td>
                    <%= link_to expense_path(expense), method: :delete, class: "btn btn-danger" do %>
                      <i class="glyphicon glyphicon-remove"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="user-column">
      <div class="user-expenseGraphs">
        <div class="user-expenseGraphHeader text-center">
            <% if @user.expenses.empty? %>
              <h3> Add Payments to Expenses to Begin Seeing Reports on Them! </h3>
            <% else %>
              <h3> Expense Reports </h3>
            <% end %>
          </div>
        <div class="user-expensesPaidCategoryColumnChart">
          <%= column_chart @user.expenses.joins(:category).group('categories.name').sum(:amount_paid), prefix: "$", xtitle: 'Category', ytitle: 'Amount Spent', title: 'Expense Spending By Category' %>
        </div>
        <div class="user-expensesPieChart">
          <%= pie_chart @user.expenses.joins(:category).group('categories.name').sum(:amount_paid), prefix: "$", legend: "right", title: 'Expense Spending By Category' %>
        </div>
      </div>
    </div>
  </div>
</div>